---
- name: Check NFS Service for Exploitability
  hosts: thx_kali
  gather_facts: no
  vars:
    target_host: "10.10.200.2"
  tasks:
    - name: Run nmap nfs-showmount script to check for exploitable NFS shares
      shell: nmap -p 2049 --script nfs-showmount {{ target_host }}
      register: nmap_result
      ignore_errors: yes
      changed_when: false  # Ensure the task is not marked as changed

    - name: Parse nmap result for exploitable NFS shares
      set_fact:
        nfs_exploitable: "{{ 'NFS export' in nmap_result.stdout }}"

    - name: Show NFS exploitability status
      debug:
        msg: >
          {% if nfs_exploitable %}
            \033[92mNFS service is exploitable\033[0m
          {% else %}
            \033[91mNFS service is not exploitable\033[0m
          {% endif %}

    - name: Fail the playbook if the NFS service is exploitable
      fail:
        msg: "NFS service on {{ target_host }} is exploitable"
      when: nfs_exploitable
      ignore_errors: true
      changed_when: false  # Ensure the task is not marked as changed
