---
- name: Check NFS Service
  hosts: thx_kali
  gather_facts: no
  vars:
    target_host: "10.10.200.2"
  tasks:
    - name: Check if NFS service is open on the host
      shell: nmap -p 2049 {{ target_host }}
      register: nmap_result
      ignore_errors: yes
      changed_when: false  # Ensure the task is not marked as changed

    - name: Parse nmap result for NFS service
      set_fact:
        nfs_service_open: "{{ '2049/tcp open' in nmap_result.stdout }}"

    - name: Show NFS service status
      debug:
        msg: >
          {% if nfs_service_open %}
            \033[92mService Open\033[0m
          {% else %}
            \033[91mService Closed\033[0m
          {% endif %}

    - name: Fail the playbook if the NFS service is not open
      fail:
        msg: "NFS service is not open on the host"
      when: not nfs_service_open
      ignore_errors: true
      changed_when: false  # Ensure the task is not marked as changed
