---
- name: Check Host Scannability with Nmap -Pn
  hosts: thx_kali
  gather_facts: no
  vars:
    target_host: "10.10.200.2"
  tasks:
    - name: Nmap -Pn scan
      shell: nmap -Pn {{ target_host }}
      register: nmap_result
      ignore_errors: yes
      changed_when: false  # Ensure the task is not marked as changed

    - name: Check nmap result for scannability
      set_fact:
        host_scannable: "{{ 'Nmap done' in nmap_result.stdout }}"

    - name: Show scannability status
      debug:
        msg: >
          {% if host_scannable %}
            \033[92mSCANNABLE\033[0m
          {% else %}
            \033[91mNOT SCANNABLE\033[0m
          {% endif %}

    - name: Fail the playbook if the host is not scannable
      fail:
        msg: "Host is not scannable"
      when: not host_scannable
      ignore_errors: true
      changed_when: false  # Ensure the task is not marked as changed
