---
- name: Nessus Scan and Log Findings
  hosts: localhost
  gather_facts: no
  vars:
    nessus_url: "https://10.10.100.3:8834"
    username: "thx"
    password: "Secure.00"
    scan_id: "1"
  tasks:
    - name: Authenticate with Nessus
      uri:
        url: "{{ nessus_url }}/session"
        method: POST
        body_format: json
        body:
          username: "{{ username }}"
          password: "{{ password }}"
        headers:
          Content-Type: "application/json"
        validate_certs: no
      register: auth_response

    - name: Set auth token
      set_fact:
        auth_token: "{{ auth_response.json.token }}"

    - name: Launch Nessus Scan
      uri:
        url: "{{ nessus_url }}/scans/{{ scan_id }}/launch"
        method: POST
        headers:
          X-Cookie: "token={{ auth_token }}"
          Content-Type: "application/json"
        validate_certs: no
      register: launch_response

    - name: Set scan UUID
      set_fact:
        scan_uuid: "{{ launch_response.json.scan_uuid }}"

    - name: Poll for Scan Status and Log Findings
      block:
        - name: Check scan status
          uri:
            url: "{{ nessus_url }}/scans/{{ scan_id }}"
            method: GET
            headers:
              X-Cookie: "token={{ auth_token }}"
              Content-Type: "application/json"
            validate_certs: no
          register: scan_status_response
          until: scan_status_response.json.info.status == "completed"
          retries: 20
          delay: 30

        - name: Log findings with timestamps
          uri:
            url: "{{ nessus_url }}/scans/{{ scan_id }}"
            method: GET
            headers:
              X-Cookie: "token={{ auth_token }}"
              Content-Type: "application/json"
            validate_certs: no
          register: scan_result

        - name: Log findings to a file
          copy:
            content: |
              {% for host in scan_result.json.hosts %}
                {% for vuln in host.vulnerabilities %}
                  Found {{ vuln.plugin_name }} at {{ lookup('pipe', 'date') }}
                {% endfor %}
              {% endfor %}
            dest: /path/to/your/logfile.log
      when: scan_status_response.json.info.status == "completed"
