---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Start Nessus scan
      uri:
        url: https://10.10.100.3:8834/scans/{{ scan_id }}/launch
        method: POST
        user: thx
        password: Secure.00
        body_format: json
        body: '{"alt_targets": "10.10.200.0/29"}'
        validate_certs: no
      register: scan_result
      delegate_to: localhost

    - name: Wait for scan to finish
      uri:
        url: https://10.10.100.3:8834/scans/{{ scan_id }}
        method: GET
        user: thx
        password: Secure.00
        validate_certs: no
      register: scan_status
      until: scan_status.json.status == "completed"
      retries: 60
      delay: 10

    - name: Get scan results
      uri:
        url: https://10.10.100.3:8834/scans/{{ scan_id }}/export
        method: POST
        user: thx
        password: Secure.00
        body_format: json
        body: '{"format": "csv"}'
        validate_certs: no
      register: export_result
      delegate_to: localhost

    - name: Save scan results to CSV file
      copy:
        content: "{{ export_result.json.file }}"
        dest: /path/to/scan_results.csv
