---
- name: Initiate Nessus Scan and Retrieve Results
  hosts: localhost
  vars:
    nessus_host: "https://10.10.100.5:8834"
    nessus_username: "thx"  # Replace with your Nessus username
    nessus_password: "Secure.00"  # Replace with your Nessus password
    nessus_scan_name: "Test Scan"
    target_hosts: "10.10.200.0/29"  # Replace with your target hosts
  tasks:
    - name: Authenticate with Nessus API
      uri:
        url: "{{ nessus_host }}/session"
        method: POST
        body_format: json
        body: >
          {
            "username": "{{ nessus_username }}",
            "password": "{{ nessus_password }}"
          }
        status_code: 200
        validate_certs: no
        return_content: yes
      register: auth_response

    - name: Set token fact
      set_fact:
        nessus_token: "{{ auth_response.json.token }}"

    - name: Create a new ad-hoc scan
      uri:
        url: "{{ nessus_host }}/scans"
        method: POST
        headers:
          X-Cookie: "token={{ nessus_token }}"
        body: >
          {
            "uuid": "ad-hoc",
            "settings": {
              "name": "{{ nessus_scan_name }}",
              "text_targets": "{{ target_hosts }}"
            }
          }
        body_format: json
        status_code: 200
        validate_certs: no
        return_content: yes
      register: scan_response

    - name: Launch the scan
      uri:
        url: "{{ nessus_host }}/scans/{{ scan_response.json.scan.id }}/launch"
        method: POST
        headers:
          X-Cookie: "token={{ nessus_token }}"
        status_code: 200
        validate_certs: no
        return_content: yes
      register: launch_response

    - name: Wait for scan to complete
      pause:
        minutes: 10  

    - name: Get scan results
      uri:
        url: "{{ nessus_host }}/scans/{{ scan_response.json.scan.id }}"
        method: GET
        headers:
          X-Cookie: "token={{ nessus_token }}"
        status_code: 200
        validate_certs: no
        return_content: yes
      register: scan_results

    - name: Parse and display vulnerabilities
      set_fact:
        vulnerabilities: "{{ scan_results.json.vulnerabilities }}"

    - name: Display vulnerabilities
      debug:
        msg: >
          Host: {{ item.host }}
          Service: {{ item.plugin_name }}
          CVE: {{ item.cve }}
          CVSS: {{ item.cvss }}
      loop: "{{ vulnerabilities }}"
