---
- name: Perform Nmap vulnerability scan and save results to XML
  hosts: thx_kali
  gather_facts: no
  tasks:
    - name: Run Nmap scan
      command: >
        nmap -sV --script=vulners -oX /home/thx/scan_results.xml 10.10.200.0/29
      register: nmap_output
      changed_when: false

    - name: Write scan results to destination file
      copy:
        content: "{{ nmap_output.stdout }}"
        dest: "/home/thx/scan_results.xml"
      when: nmap_output is succeeded and nmap_output.stdout != ""

    - name: Send scan results to remote host
      command: >
        sshpass -p 'Secure.00' scp -o StrictHostKeyChecking=no /home/thx/scan_results.xml thx@10.10.100.4:/tmp/scan_results.xml
      delegate_to: localhost
      when: nmap_output is succeeded and nmap_output.stdout != ""
