---
- name: Perform Nmap vulnerability scan and save results to XML
  hosts: thx_kali
  gather_facts: no
  tasks:
    - name: Run Nmap scan
      command: >
        nmap -sV --script=vulners -oX /home/thx/scan_results.xml 10.10.200.0/29
      register: nmap_output
      changed_when: false

    - name: Send scan results to remote host
      command: >
        sshpass -p 'Secure.00' scp -o StrictHostKeyChecking=no /home/thx/scan_results.xml thx@10.10.100.4:/tmp/scan_results.xml
      delegate_to: localhost
