---
- name: Perform Nmap vulnerability scan and save results to XML
  hosts: thx_kali
  gather_facts: no
  vars_prompt:
    - name: target_ip_range
      prompt: "Enter the target IP range to scan (e.g., 10.10.200.0/29): "
      private: no

  tasks:
    - name: Run Nmap scan
      command: >
        nmap -sV --script=vulners -oX /home/thx/scan_results.xml {{ target_ip_range }}
      register: nmap_output
      changed_when: false

    - name: Copy scan results XML file to remote machine
      ansible.builtin.copy:
        src: /home/thx/scan_results.xml
        dest: /tmp/scan_results.xml
        remote_src: yes
      delegate_to: 10.10.100.4
      when: nmap_output is succeeded

