---
- name: Perform Nmap vulnerability scan and capture results in XML format
  hosts: thx_kali
  gather_facts: no
  tasks:
    - name: Run Nmap scan and capture output in XML format
      shell: >
        nmap -sV --script=vulners -oX -
      register: nmap_output
      changed_when: false
      args:
        chdir: /home/thx  # Change to the directory where you want to store the result file

    - name: Write Nmap scan results to file on Ansible control machine
      ansible.builtin.copy:
        content: "{{ nmap_output.stdout }}"
        dest: "/tmp/scan_results.xml"
