---
- name: PERFORM VULNERABILITY SCAN ON TARGET SUBNET
  hosts: thx_kali
  gather_facts: no
  tasks:
    - name: RUNNING NMAP SCAN
      command: >
        nmap -sV --script=vulners -oX /home/thx/scan_results.xml 10.10.200.0/29
      register: nmap_output
      changed_when: false

    - name: READ NMAP SCAN RESULTS
      command: cat /home/thx/scan_results.xml
      register: scan_results

    - name: DISPLAY NMAP SCAN RESULTS
      debug:
        msg: "{{ scan_results.stdout }}"

    - name: FETCH NMAP SCAN RESULTS TO LOCALHOST
      fetch:
        src: /home/thx/scan_results.xml
        dest: /tmp/
        flat: yes

- name: DISPLAY SCAN RESULTS ON LOCALHOST
  hosts: localhost
  gather_facts: no
  tasks:
    - name: DISPLAY LOCAL SCAN RESULTS
      command: cat /tmp/scan_results.xml
      register: local_scan_results

    - name: DISPLAY LOCAL NMAP SCAN RESULTS
      debug:
        msg: "{{ local_scan_results.stdout }}"
