---
- name: Perform Nmap vulnerability scan and save results to XML
  hosts: thx_kali
  gather_facts: no
  tasks:
    - name: Run Nmap scan
      command: >
        nmap -sV --script=vulners -oX /home/thx/scan_results.xml 10.10.200.0/29
      register: nmap_output
      changed_when: false

    - name: Fetch scan results XML file
      fetch:
        src: /home/thx/scan_results.xml
        dest: /tmp
        flat: yes  # Ensures that only the file name is used in the destination path
        delegate_to: localhost  # Execute the task on the control machine
      when: nmap_output is succeeded

    - name: Copy file to remote Ansible host
      ansible.builtin.copy:
        src: "/tmp/scan_results.xml"
        dest: "/tmp/scan_results.xml"  # Change destination path as needed
        remote_src: yes
      delegate_to: 10.10.100.4
