---
- name: PERFORM VULNERABILITY SCAN ON TARGET SUBNET
  hosts: thx_kali
  gather_facts: no
  tasks:
    - name: RUNNING NMAP SCAN
      command: >
        nmap -sV --script=vulners -oX /home/thx/scan_results.xml 10.10.200.0/29
      register: nmap_output
      changed_when: false

    - name: READ NMAP SCAN RESULTS
      command: cat /home/thx/scan_results.xml
      register: scan_results

    - name: DISPLAY NMAP SCAN RESULTS
      debug:
        msg: "{{ scan_results.stdout }}"
