---
- name: Perform Nmap vulnerability scan and save results to XML
  hosts: thx_kali
  gather_facts: no
  tasks:
    - name: Run Nmap scan
      command: >
        nmap -sV --script=vulners -oX /home/thx/scan_results.xml 10.10.200.0/29
      register: nmap_output
      changed_when: false

    - name: Fetch scan results XML file
      fetch:
        src: /home/thx/scan_results.xml
        dest: /home/thx
      when: nmap_output is succeeded
