---
- name: Ping Gateways
  hosts: thx_kali
  gather_facts: no

  tasks:
    - name: Ping Gateway
      raw: ping -c 1 -W 1 -q {{ ansible_default_ipv4.gateway }}
      ignore_errors: yes
      register: gateway_ping_result

    - name: Check Gateway Availability
      set_fact:
        gateway_available: "{{ 'reachable' if gateway_ping_result.rc == 0 else 'unreachable' }}"
      delegate_to: localhost

    - debug:
        msg: "Gateway {{ ansible_default_ipv4.gateway }} is {{ gateway_available }}"
