---
- name: Get interface details
  hosts: thx_nessus
  gather_facts: yes
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
    - name: Display interface details
      ansible.builtin.debug:
        var: ansible_facts.interfaces
