---
- name: Update hosts to the latest patches
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      yum:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      yum:
        name: '*'
        state: latest
