---
- name: Check network configurations
  hosts: thx_kali
  gather_facts: true
  tasks:
    - name: Gather network facts
      ansible.builtin.setup:
        filter: 'ansible_(interfaces|default_ipv4)'
      register: network_facts

    - name: Display network configurations
      debug:
        msg: |
          Interface: {{ item.key }}
          IP Address: {{ item.value.ipv4.address }}
          Netmask: {{ item.value.ipv4.netmask }}
          Gateway: {{ item.value.ipv4.gateway }}
      loop: "{{ network_facts['ansible_interfaces'] }}"
      when: network_facts['ansible_{{ item }}']['ipv4'] is defined
