---
- name: Check Node Reachability
  hosts: thx_kali
  gather_facts: no
  vars:
    target_host: "10.10.200.2"
  tasks:
    - name: Ping test
      ping:
      ignore_unreachable: yes
      register: ping_result

    - name: Nmap aggressive test
      shell: nmap -A -T4 {{ target_host }}
      register: nmap_result
      ignore_errors: yes

    - name: Check nmap result for reachability
      set_fact:
        nmap_reachable: "{{ 'Host seems down' not in nmap_result.stdout }}"
        
    - name: Determine overall reachability
      set_fact:
        node_reachable: "{{ (ping_result.ping is defined and ping_result.ping == 'pong') or nmap_reachable }}"
    
    - name: Show reachability status
      debug:
        msg: >
          {% if node_reachable %}
            \033[92mREACHABLE\033[0m
          {% else %}
            \033[91mNOT REACHABLE\033[0m
          {% endif %}
